"""new fields in user model

Revision ID: 41eff506d5ee
Revises: dc01856eb0f2
Create Date: 2019-10-11 10:52:14.663883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41eff506d5ee'
down_revision = 'dc01856eb0f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
